
name: Server tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install datalad-installer
          datalad-installer datalad git-annex
          export PATH="$PATH:/usr/share/miniconda/bin"
          echo which git-annex
          which git-annex
          echo which datalad
          which datalad
          datalad --version
          if [ -f requirements-devel.txt ]; then pip install -r requirements-devel.txt; fi
          pip install datalad --upgrade
          which datalad
          datalad --version
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --ignore E501,E722,E402 --show-source --statistics
      - name: Test with pytest
        run: |
          export PATH="$PATH:/usr/share/miniconda/bin"
          git config --global user.email "github-test@example.com"
          git config --global user.name "Github Testscript"
          pytest
